In [2]:
# Data Analysis with Python

In [14]:
import sys
import numpy as np

# Basic NumPy Arrays

In [15]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [16]:
a = np.array([1, 2, 3, 4])

In [17]:
b = np.array([0, .5, 1, 1.5, 2])

In [18]:
a[0], a[1]

(1, 2)

In [19]:
a[0:]

array([1, 2, 3, 4])

In [20]:
a[1:3]

array([2, 3])

In [21]:
a[1:-1]

array([2, 3])

In [22]:
a[::2]

array([1, 3])

In [23]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [24]:
b[[0, 2, -1]]

array([0., 1., 2.])

 ## Array Types

In [26]:
a

array([1, 2, 3, 4])

In [27]:
a.dtype

dtype('int32')

In [28]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [29]:
b.dtype

dtype('float64')

In [30]:
c = np.array(["a", "b", "c"])

In [31]:
c.dtype

dtype('<U1')

## Dimensions and shapes

In [32]:
A = np.array([
    [1, 2, 3], 
    [4, 5, 6]
])

In [33]:
A.shape

(2, 3)

In [34]:
A.ndim

2

In [35]:
A.size

6

In [36]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7]
    ], 
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [37]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [38]:
B.shape

(2, 2, 3)

In [39]:
B.ndim

3

In [40]:
B.size

12

## Indexing and Slicing of Matrices

In [43]:
# Square matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [44]:
A[1]

array([4, 5, 6])

In [45]:
A[0]

array([1, 2, 3])

In [46]:
A[1][0]

4

In [47]:
A[1, 0]

4

In [48]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [50]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [51]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
A[1] = np.array([10, 10, 10])

In [53]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [54]:
A[2] = 99

In [55]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

## Summary statistics

In [56]:
a = np.array([1, 2, 3, 4])

In [57]:
a.sum()

10

In [58]:
a.mean()

2.5

In [59]:
a.std()

1.118033988749895

In [60]:
a.var()

1.25

In [61]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [62]:
A.sum()

45

In [63]:
A.mean()

5.0

In [65]:
A.std()

2.581988897471611

In [66]:
A.sum(axis=0)

array([12, 15, 18])

In [67]:
A.sum(axis=1)

array([ 6, 15, 24])

In [68]:
A.mean(axis=0)

array([4., 5., 6.])

In [69]:
A.mean(axis=1)

array([2., 5., 8.])

In [70]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [71]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

## Broadcasting and Vectorized operations

In [72]:
a = np.arange(4)

In [73]:
a

array([0, 1, 2, 3])

In [74]:
a + 10

array([10, 11, 12, 13])

In [75]:
a * 10

array([ 0, 10, 20, 30])

In [76]:
a

array([0, 1, 2, 3])

In [77]:
a += 100

In [78]:
a

array([100, 101, 102, 103])

In [79]:
a = np.arange(4)

In [80]:
a

array([0, 1, 2, 3])

In [81]:
b = np.array([10, 10, 10, 10])

In [82]:
b

array([10, 10, 10, 10])

In [83]:
a + b

array([10, 11, 12, 13])

In [84]:
a * b

array([ 0, 10, 20, 30])

## Boolean arrays (masks)

In [85]:
a = np.arange(4)

In [86]:
a

array([0, 1, 2, 3])

In [87]:
a[[0, -1]]

array([0, 3])

In [88]:
a[[True, False, False, True]]

array([0, 3])

In [89]:
a >= 2

array([False, False,  True,  True])

In [90]:
a[a >= 2]

array([2, 3])

In [91]:
a.mean()

1.5

In [92]:
a[a > a.mean()]

array([2, 3])

In [93]:
a[~(a > a.mean())]

array([0, 1])

In [94]:
A = np.random.randint(100, size=(3, 3))

In [97]:
A

array([[34,  9, 35],
       [ 8, 60, 35],
       [94, 41, 86]])

In [99]:
A > 30

array([[ True, False,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [100]:
A[A > 30]

array([34, 35, 60, 35, 94, 41, 86])

## Linear Algebra

In [101]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [102]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [103]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [104]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [105]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [106]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [113]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])